<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Seatify</RootNamespace>
    <AssemblyName>Seatify</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MCGalaxy">
      <HintPath>../MCGalaxy/MCGalaxy_.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>